sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: IRp861tQdSL7CiEITafq0yzMtoRkpilGZLJwJ2oT2tQI1tPoGEIaYNj8hWrGWHY1c+06ZJ0kIJYK0BirvxAH/Svn1nxjtiiCxf88/KtoA131IfAlBldzUEkJCLm19iUGtW4Yr50IRAlEgWZWpEFLVD9iKKmIAGpYBy7e20Wr2lrxgTZVWfb6IZ+JPL7dr9XiFz/6BOpkYuzY3muWWC0k0gd0j7eGGNlkP+f0+kBA9DkxvY2EkrltqQ9n5uJ9WaV9rEQvYrv55ow5v01LcqxqFOZJ0QUXCV2WC1a4kNw4HBILuUxAoEQ1+QkBSNGp2TSrGLddR5hy1aCZwiElHquFRUXkhed7Y5Uk5RL4K35CL21bpoOdaCx/Q8YOAcLnJimuygM7Nxn3Q1x+Ve+nZeeWbOX7ej4x4PSMZy5xos2uC4la8qZladslE2u3fetBd4TUkuhDMxIxGeRna5AwnlwQ7TFZmAJxsf7YkrTdz0n8aDrs+fWKMI5Ja+3BSZP9j5mkoVkfp0mrwGzUgz4B4Mdx2u1oUm9P7+xhRfTYxoFpqlyj7bFhP9e8G/d1sQyw5/iAB+CgclELtpb7fYDe83zs9d49DEsdVHZ9yilXscP+04PZ8XU3lzx46XoSjSx6FqH9GWoVFRH5nzBQ7tthgn9V95+74eZkae1zjul13Cfu6gI=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Three-Men-in-a-Boat_308
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy